### PR TITLE
os: adds .putenv() method

### PR DESCRIPTION
**Pull request by MaxTurchin**
Needed realpath and putenv functionality for my work. Though this might be of use :)

### CODE REVIEW

**Comment by pfalcon** [comment]
Adding these would be useful, thanks for looking into that!

The common recommendation is to open one PR per one feature. Let's concentrate of os.putenv() first. There're at least 2 issues: 1) What you implemented doesn't correspond to os.putenv() signature: https://docs.python.org/3/library/os.html#os.putenv; 2) please do "git log", and try to write your commit message as close as possible to what's already in git log.

Thanks!

**Comment by MaxTurchin** [comment]
Sure thing!
I think my latest change does the trick.
I'll open another PR for os.path.realpath ()

**Comment by pfalcon** [comment]
Thanks for splitting it and for updates.

> os: Add .putenv() method

You picked just the right format for commit messages: package name, colon, then description with capital letter (I also put dot at the end, but don't nitpick others up to that ;-) ). Please check the realpath patches for that format.

Also, putenv() if the function, not method, so I updated the message after all.

**Comment by pfalcon** [comment]
Another useful thing to do is to add a test (if easily possible), or if not, a manual example a human can run and check that the function (still) works as expected. I added a kinda-test in https://github.com/pfalcon/pycopy-lib/blob/master/os/test_putenv.py.

**Comment by pfalcon** [comment]
Merged/released on PyPI, thanks!

**Pull request closed without merging**
